import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
    title: 'ChartDB - Database schema diagrams visualizer',
    description:
        'Free and Open-source database diagrams editor, visualize and design your database with a single query.',
    openGraph: {
        title: 'ChartDB - Database schema diagrams visualizer',
        description:
            'Free and Open-source database diagrams editor, visualize and design your database with a single query.',
        images: ['https://app.chartdb.io/chartdb.png'],
        url: 'https://app.chartdb.io',
        type: 'website',
        siteName: 'ChartDB',
    },
    twitter: {
        card: 'summary_large_image',
        title: 'ChartDB - Database schema diagrams visualizer',
        description:
            'Free and Open-source database diagrams editor, visualize and design your database with a single query.',
        images: [
            'https://github.com/chartdb/chartdb/raw/main/public/chartdb.png',
        ],
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="h-full">
            <head>
                {/* Runtime config — sets window.env before the React bundle runs.
                    Generated by docker-entrypoint.sh from container env vars,
                    enabling runtime injection without a rebuild. */}
                <script src="/config.js" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className="h-full">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
